modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="rituals_of_the_wilds"
version="1.0.4"
displayName="Rituals of the Wilds"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Thanks for models to TheNorthernHarpy, Thanks to Ember for structures, JenkiMods for coding"
authors="JenkiMods, Thenorthernharpy, emberunholy"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rituals_of_the_wilds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.rituals_of_the_wilds]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration